services:
  mongo1:
    image: mongo
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
    ports:
      - 27017:27017
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'127.0.0.1:27017'}]}) }" | mongosh --port 27017 --quiet
      interval: 5s
      timeout: 30s
      start_period: 0s
      start_interval: 1s
      retries: 30
    volumes:
      - $HOME/docker_volumes/mongo/data/db:/data/db
  redis-stack:
    image: redis/redis-stack:latest
    container_name: redis-stack
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - $HOME/docker_volumes/redis/data:/data
    restart: always
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: aman
      POSTGRES_PASSWORD: aman
    ports:
      - "5432:5432"
    volumes:
      - $HOME/docker_volumes/postgres/data:/var/lib/postgresql/data
    restart: always
