services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "3009:8080"
    environment:
      - TZ=UTC
    volumes:
      - $HOME/docker_volumes/open-webui/open-webui:/app/backend/data
    restart: always
