services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "3009:8080"
    environment:
      - TZ=UTC
    volumes:
      - $HOME/docker_volumes/open-webui/open-webui:/app/backend/data
    restart: always
  pipelines:
    image: ghcr.io/open-webui/pipelines:main
    container_name: pipelines
    ports:
      - "9099:9099"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - $HOME/docker_volumes/open-webui/pipelines:/app/pipelines
    restart: always
volumes:
  open-webui:
  pipelines:
