[colors]
[colors.primary]
foreground = "#ffffff"  
background = "#1C1C1C"  

[colors.cursor]
text = "#000000"  
cursor = "#38ff9d"  

[colors.search.matches]
background = "#38ff9c"  

[colors.selection]
background = "#38ff9c"  

[colors.normal]
black = "#0b3b61"  
red = "#ff3a3a"  
green = "#52ffd0"  
yellow = "#fff383"  
blue = "#1376f9"  
magenta = "#c792ea"  
cyan = "#ff5ed4"  
white = "#16fda2"  

[colors.bright]
black = "#63686d"  
red = "#ff54b0"  
green = "#74ffd8"  
yellow = "#fcf5ae"  
blue = "#388eff"  
magenta = "#ae81ff"  
cyan = "#ff6ad7"  
white = "#60fbbf"  

[font]
normal = { family = "Iosevka", style = "Regular" }  
bold = { style = "Bold" }  
italic = { style = "Regular" }  
bold_italic = { style = "Bold" }  
size = 20

[window]
startup_mode = "Maximized"
