-- require other scripts
require("aman.plugins-setup")
require("aman.core.colorscheme")
require("aman.core.options")
require("aman.core.keymaps")
require("aman.core.custom")
require("aman.plugins.comment")
require("aman.plugins.nvim-tree")
require("aman.plugins.lualine")
require("aman.plugins.telescope")
require("aman.plugins.nvim-cmp")
require("aman.plugins.lsp.lspconfig")
require("aman.plugins.lsp.null-ls")
require("aman.plugins.lsp.mason")
require("aman.plugins.autopairs")
require("aman.plugins.treesitter")
require("aman.plugins.gitsigns")
require("aman.plugins.devicons")
